version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlinx:*"
      spring:
        patterns:
          - "org.springframework*:*"
      test-tools:
        patterns:
          - "org.junit*:*"
          - "org.assertj:*"
          - "io.mockk:*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "ci"
