spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/components_registry
    username: crs
    password: crs
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=300s

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO
