auth-server:
  url: http://localhost:8180
  realm: f1

octopus-security:
  roles:
    ROLE_ANONYMOUS:
      - ACCESS_COMPONENTS
    ROLE_ADMIN:
      - ACCESS_COMPONENTS
      - EDIT_COMPONENTS
      - ARCHIVE_COMPONENTS
      - RENAME_COMPONENTS
      - DELETE_COMPONENTS
      - IMPORT_DATA
      - ACCESS_AUDIT
