components-registry:
  vcs:
    root: # envFile property
    username: # envFile property
    password: # envFile property

  work-dir: /tmp/components-registry
  version-name:
    service-branch: serviceCBranch
    service: serviceC
    minor: minorC
